-- =====================================================
-- Script: encryption_demo.sql
-- Purpose: Encrypt and decrypt data using DBMS_CRYPTO
-- Author: Jesus Bastidas
-- Environment: Oracle 19c
-- =====================================================

CREATE TABLE encrypted_data (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encrypted_value RAW(2000)
);

CREATE OR REPLACE PROCEDURE encrypt_decrypt_demo (
    p_value IN VARCHAR2,
    p_encrypted_value OUT RAW,
    p_decrypted_value OUT VARCHAR2
) IS
    l_key RAW(32) := UTL_RAW.CAST_TO_RAW('12345678901234567890123456789012');
    l_iv RAW(16) := UTL_RAW.CAST_TO_RAW('1234567890123456');
BEGIN
    p_encrypted_value := DBMS_CRYPTO.ENCRYPT(
        src => UTL_I18N.STRING_TO_RAW(p_value, 'AL32UTF8'),
        typ => DBMS_CRYPTO.ENCRYPT_AES256 +
               DBMS_CRYPTO.CHAIN_CBC +
               DBMS_CRYPTO.PAD_PKCS5,
        key => l_key,
        iv => l_iv
    );

    p_decrypted_value := UTL_I18N.RAW_TO_CHAR(
        DBMS_CRYPTO.DECRYPT(
            src => p_encrypted_value,
            typ => DBMS_CRYPTO.ENCRYPT_AES256 +
                   DBMS_CRYPTO.CHAIN_CBC +
                   DBMS_CRYPTO.PAD_PKCS5,
            key => l_key,
            iv => l_iv
        ),
        'AL32UTF8'
    );
END;
/
